
site_name: geogeek

theme:
  name: material
  palette:
    primary: purple
  icon:
    logo: material/console
  custom_dir: overrides #-- to override the copyright

repo_url: https://github.com/hugoledoux/geogeek

# nav:
#     - Home: index.md


edit_uri: edit/main/docs/
repo_name: hugoledoux/geogeek


# plugins:
#   - search
#   - mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
